import { Language, TranslationSet } from './types.ts';

export const CSV_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjY5PdR1CTA2gcvbeIPSFYflT2WHKWxELGliEG8c-fcCm9KlpTBlTbUIMDTCH1SieAITuY02SS65ic/pub?gid=0&single=true&output=csv";

export const I18N: Record<Language, TranslationSet> = {
  zh: {
    title: "原管貨櫃管理報表 v7.5",
    liveStatus: "🚚 貨櫃動態管理 (07:00-07:00)",
    totalUnits: "累計車次",
    avgRate: "平均達成率",
    pareto: "📊 柏拉圖分析 (原材料種類 TOP 10)",
    frequency: "📦 每日車次頻率趨勢",
    tonnage: "⚖️ 每日入廠噸數分析",
    efficiency: "⏱️ 作業時間分析",
    flow: "🔥 24H 作業流量分佈",
    settings: "看板與數據設定",
    save: "確認並套用設定",
    update: "立即更新數據",
    benchmark: "⏱️ 每車平均工時 (基準)",
    threshold: "🚨 達成率警示門檻 (%)",
    targetHoursLabel: "🎯 每日目標作業時數 (H)",
    aiInsights: "🤖 AI 智慧洞察 (限登入)",
    askAi: "分析數據趨勢",
    analyzing: "正在分析中...",
    arrival: "進場時間",
    departure: "結束時間",
    rate: "達成率",
    effAvg: "每車平均工時",
    effTotal: "當日作業時間加總",
    selectDate: "選擇日期",
    analysisTitle: "分析資料如下",
    statTop10: "TOP 10 總重",
    statRangeTotal: "區間總重",
    statRatio: "佔比 (%)",
    statAvgDayWeight: "日均重量",
    statTotalUnits: "總車次",
    statTotalWorkTime: "總工時(分)",
    statAvgDayUnits: "日均車次",
    statTotalEntryUnits: "貨櫃入廠車次",
    statAvgWorkTime: "每車平均工時",
    statTimeDist: "平均作業時間分佈",
    statOperationRate: "稼動率 (%)",
    operationRateFormula: "計算式: (基準工時 / 實際作業時間) * 100",
    chartAnimation: "看板動態動畫設定",
    animationStatus: "動畫狀態",
    animationDurationLabel: "動畫循環間隔 (S)",
    on: "開啟",
    off: "關閉",
    loginRequired: "請先登入帳號以使用 AI 智慧洞察功能",
    loginAction: "登入帳號",
    logoutAction: "登出",
    statFetchDays: "資料抓取天數"
  },
  en: {
    title: "Logistics Dashboard v7.5",
    liveStatus: "🚚 Live Status Management (07:00-07:00)",
    totalUnits: "Total Units",
    avgRate: "Avg Rate",
    pareto: "📊 Pareto Analysis (Material Type TOP 10)",
    frequency: "📦 Frequency Trends",
    tonnage: "⚖️ Daily Tonnage Analysis",
    efficiency: "⏱️ Work Time Analysis",
    flow: "🔥 24H Operation Flow",
    settings: "Dashboard Settings",
    save: "Save & Apply Settings",
    update: "Update Now",
    benchmark: "⏱️ Avg Time per Truck (Base)",
    threshold: "🚨 Rate Warn Threshold (%)",
    targetHoursLabel: "🎯 Target Work Hours (H)",
    aiInsights: "🤖 AI Smart Insights",
    askAi: "Analyze Trends",
    analyzing: "Analyzing...",
    arrival: "Entry Time",
    departure: "End Time",
    rate: "Rate",
    effAvg: "Avg Time per Truck",
    effTotal: "Daily Total Work Time",
    selectDate: "Select Date",
    analysisTitle: "Analysis Data Summary",
    statTop10: "TOP 10 Weight",
    statRangeTotal: "Range Total",
    statRatio: "Ratio (%)",
    statAvgDayWeight: "Avg Day Weight",
    statTotalUnits: "Total Units",
    statTotalWorkTime: "Total Time(m)",
    statAvgDayUnits: "Avg Day Units",
    statTotalEntryUnits: "Total Entries",
    statAvgWorkTime: "Avg Time per Truck",
    statTimeDist: "Time Distribution",
    statOperationRate: "Operation Rate (%)",
    operationRateFormula: "Formula: (Base / Actual) * 100",
    chartAnimation: "Dashboard Dynamic Settings",
    animationStatus: "Animation Status",
    animationDurationLabel: "Animation Interval (S)",
    on: "On",
    off: "Off",
    loginRequired: "Please log in",
    loginAction: "Sign In",
    logoutAction: "Sign Out",
    statFetchDays: "Fetch Days"
  },
  hi: {
    title: "रसद डैशबोर्ड v7.5",
    liveStatus: "🚚 लाइव स्थिति प्रबंधन (07:00-07:00)",
    totalUnits: "कुल इकाइयां",
    avgRate: "औसत दर",
    pareto: "📊 पारेतो विश्लेषण (सामग्री प्रकार TOP 10)",
    frequency: "📦 आवृत्ति रुझान",
    tonnage: "⚖️ दैनिक वजन विश्लेषण",
    efficiency: "⏱️ कार्य समय विश्लेषण",
    flow: "🔥 24H ऑपरेशन प्रवाह",
    settings: "看板 सेटिंग्स",
    save: "सहेजें और लागू करें",
    update: "अभी अपडेट करें",
    benchmark: "⏱️ प्रति ट्रक औसत समय",
    threshold: "🚨 चेतावनी सीमा (%)",
    targetHoursLabel: "🎯 दैनिक लक्ष्य घंटे (H)",
    aiInsights: "🤖 AI अंतर्दृष्टि",
    askAi: "रुझानों का विश्लेषण करें",
    analyzing: "विश्लेषण हो रहा है...",
    arrival: "प्रवेश समय",
    departure: "निकास समय",
    rate: "दर",
    effAvg: "प्रति ट्रक औसत समय",
    effTotal: "दैनिक कार्य समय",
    selectDate: "तारीख चुनें",
    analysisTitle: "विश्लेषण डेटा",
    statTop10: "शीर्ष 10 वजन",
    statRangeTotal: "कुल वजन",
    statRatio: "अनुपात (%)",
    statAvgDayWeight: "औसत वजन/दिन",
    statTotalUnits: "कुल इकाइयां",
    statTotalWorkTime: "कुल समय (मिनट)",
    statAvgDayUnits: "औसत इकाइयां/दिन",
    statTotalEntryUnits: "कुल प्रविष्टियां",
    statAvgWorkTime: "प्रति ट्रक औसत समय",
    statTimeDist: "समय वितरण",
    statOperationRate: "परिचालन दर (%)",
    operationRateFormula: "सूत्र: (बेस / वास्तविक) * 100",
    chartAnimation: "एनीमेशन सेटिंग्स",
    animationStatus: "स्थिति",
    animationDurationLabel: "अंतराल (S)",
    on: "चालू",
    off: "बंद",
    loginRequired: "लॉग इन करें",
    loginAction: "लॉग इन करें",
    logoutAction: "साइन आउट",
    statFetchDays: "फ़ेच दिन"
  }
};
